import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import ErrorBoundary from '@/components/ErrorHandling/ErrorBoundary'
import { Toaster } from 'react-hot-toast'
import { NotificationProvider } from '@/components/NotificationContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: "Find The Picture You Want",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
          <NotificationProvider>
            <ErrorBoundary>
              <Navbar />
              {children}
              <Toaster 
                position="top-center"
                toastOptions={{
                  duration: 3000,
                  style: {
                    background: '#1f2937',
                    color: '#f9fafb',
                    border: '1px solid #374151',
                    borderRadius: '12px',
                    fontWeight: '500',
                  },
                }}
              />
            </ErrorBoundary>
          </NotificationProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
